CREATE DATABASE PAYNEARBY;
USE PAYNEARBY;

/*
drop table DIM_PINCODE;
drop table STG_PINCODE;
*/

create table DIM_PINCODE(
ID VARCHAR(20) primary key,
PLACE_NAME VARCHAR(50),
ADMIN_NAME VARCHAR(50),
LATITUDE FLOAT,
LONGITUDE FLOAT,
ACCURACY INT,
LOAD_DATE datetime
);

create table STG_PINCODE(
ID VARCHAR(20),
PLACE_NAME VARCHAR(50),
ADMIN_NAME VARCHAR(50),
LATITUDE FLOAT,
LONGITUDE FLOAT,
ACCURACY INT
);